name: build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: make ci
      - run: npm run codecov
